services:
  - type: web
    name: ams-backend
    env: node
    root: backend
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
      - key: PORT
        fromService:
          type: web
          name: ams-backend
          property: port
